# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\lenovo\Desktop\TUP-Cavite Files\2nd Year College [Skwl Shts]\2nd Sem\Software Design [CPET 8]\Inventory System TUP-C UITC [GUI]\Create Account.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateAccountWindow(object):
    def setupUi(self, CreateAccountWindow):
        CreateAccountWindow.setObjectName("CreateAccountWindow")
        CreateAccountWindow.resize(644, 991)
        CreateAccountWindow.setMinimumSize(QtCore.QSize(644, 991))
        CreateAccountWindow.setMaximumSize(QtCore.QSize(644, 991))
        CreateAccountWindow.setStyleSheet("background-color: rgb(58, 58, 58);")
        self.centralwidget = QtWidgets.QWidget(CreateAccountWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CreateAccountCreateUsernameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.CreateAccountCreateUsernameLineEdit.setGeometry(QtCore.QRect(180, 590, 291, 41))
        self.CreateAccountCreateUsernameLineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.CreateAccountCreateUsernameLineEdit.setMaxLength(64)
        self.CreateAccountCreateUsernameLineEdit.setObjectName("CreateAccountCreateUsernameLineEdit")
        self.CreateAccountSignUpPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.CreateAccountSignUpPushButton.setGeometry(QtCore.QRect(160, 820, 331, 71))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.CreateAccountSignUpPushButton.setFont(font)
        self.CreateAccountSignUpPushButton.setStyleSheet("background-color: rgb(195, 29, 57);\n"
"color: rgb(255, 255, 255);")
        self.CreateAccountSignUpPushButton.setObjectName("CreateAccountSignUpPushButton")
        self.CreateAccountCreatePasswordLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.CreateAccountCreatePasswordLineEdit.setGeometry(QtCore.QRect(180, 670, 291, 41))
        self.CreateAccountCreatePasswordLineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.CreateAccountCreatePasswordLineEdit.setMaxLength(16)
        self.CreateAccountCreatePasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.CreateAccountCreatePasswordLineEdit.setObjectName("CreateAccountCreatePasswordLineEdit")
        self.CreateAccountLbl = QtWidgets.QLabel(self.centralwidget)
        self.CreateAccountLbl.setGeometry(QtCore.QRect(200, 190, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.CreateAccountLbl.setFont(font)
        self.CreateAccountLbl.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"color: rgb(255, 255, 255);")
        self.CreateAccountLbl.setObjectName("CreateAccountLbl")
        self.CreateAccountLogoLbl = QtWidgets.QLabel(self.centralwidget)
        self.CreateAccountLogoLbl.setGeometry(QtCore.QRect(280, 60, 111, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CreateAccountLogoLbl.sizePolicy().hasHeightForWidth())
        self.CreateAccountLogoLbl.setSizePolicy(sizePolicy)
        self.CreateAccountLogoLbl.setStyleSheet("border-image: url(:/Icons/CREATE ACCOUNT.png);\n"
"background-color: rgb(48, 48, 48);\n"
"border-radius: 10px;")
        self.CreateAccountLogoLbl.setText("")
        self.CreateAccountLogoLbl.setObjectName("CreateAccountLogoLbl")
        self.CreateAccountCreatePasswordLbl = QtWidgets.QLabel(self.centralwidget)
        self.CreateAccountCreatePasswordLbl.setGeometry(QtCore.QRect(180, 650, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.CreateAccountCreatePasswordLbl.setFont(font)
        self.CreateAccountCreatePasswordLbl.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"color: rgb(255, 255, 255);")
        self.CreateAccountCreatePasswordLbl.setObjectName("CreateAccountCreatePasswordLbl")
        self.CreateAccountBGLbl = QtWidgets.QLabel(self.centralwidget)
        self.CreateAccountBGLbl.setGeometry(QtCore.QRect(40, 40, 561, 911))
        self.CreateAccountBGLbl.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"border-radius: 10px;")
        self.CreateAccountBGLbl.setText("")
        self.CreateAccountBGLbl.setObjectName("CreateAccountBGLbl")
        self.CreateAccountCreateUsernameLbl = QtWidgets.QLabel(self.centralwidget)
        self.CreateAccountCreateUsernameLbl.setGeometry(QtCore.QRect(180, 570, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.CreateAccountCreateUsernameLbl.setFont(font)
        self.CreateAccountCreateUsernameLbl.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"color: rgb(255, 255, 255);")
        self.CreateAccountCreateUsernameLbl.setObjectName("CreateAccountCreateUsernameLbl")
        self.CreateAccountConfirmPasswordLbl = QtWidgets.QLabel(self.centralwidget)
        self.CreateAccountConfirmPasswordLbl.setGeometry(QtCore.QRect(180, 730, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.CreateAccountConfirmPasswordLbl.setFont(font)
        self.CreateAccountConfirmPasswordLbl.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"color: rgb(255, 255, 255);")
        self.CreateAccountConfirmPasswordLbl.setObjectName("CreateAccountConfirmPasswordLbl")
        self.CreateAccountConfirmPasswordLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.CreateAccountConfirmPasswordLineEdit.setGeometry(QtCore.QRect(180, 750, 291, 41))
        self.CreateAccountConfirmPasswordLineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.CreateAccountConfirmPasswordLineEdit.setMaxLength(16)
        self.CreateAccountConfirmPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.CreateAccountConfirmPasswordLineEdit.setObjectName("CreateAccountConfirmPasswordLineEdit")
        self.CreateAccountLastNameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.CreateAccountLastNameLineEdit.setGeometry(QtCore.QRect(180, 430, 291, 41))
        self.CreateAccountLastNameLineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.CreateAccountLastNameLineEdit.setMaxLength(64)
        self.CreateAccountLastNameLineEdit.setObjectName("CreateAccountLastNameLineEdit")
        self.CreateAccountLastNameLbl = QtWidgets.QLabel(self.centralwidget)
        self.CreateAccountLastNameLbl.setGeometry(QtCore.QRect(180, 410, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.CreateAccountLastNameLbl.setFont(font)
        self.CreateAccountLastNameLbl.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"color: rgb(255, 255, 255);")
        self.CreateAccountLastNameLbl.setObjectName("CreateAccountLastNameLbl")
        self.CreateAccountFirstNameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.CreateAccountFirstNameLineEdit.setGeometry(QtCore.QRect(180, 270, 291, 41))
        self.CreateAccountFirstNameLineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.CreateAccountFirstNameLineEdit.setMaxLength(64)
        self.CreateAccountFirstNameLineEdit.setObjectName("CreateAccountFirstNameLineEdit")
        self.CreateAccountFirstNameLbl = QtWidgets.QLabel(self.centralwidget)
        self.CreateAccountFirstNameLbl.setGeometry(QtCore.QRect(180, 250, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CreateAccountFirstNameLbl.setFont(font)
        self.CreateAccountFirstNameLbl.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"color: rgb(255, 255, 255);")
        self.CreateAccountFirstNameLbl.setObjectName("CreateAccountFirstNameLbl")
        self.CreateAccountChooseAccountTypeGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.CreateAccountChooseAccountTypeGroupBox.setGeometry(QtCore.QRect(180, 500, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.CreateAccountChooseAccountTypeGroupBox.setFont(font)
        self.CreateAccountChooseAccountTypeGroupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.CreateAccountChooseAccountTypeGroupBox.setFlat(False)
        self.CreateAccountChooseAccountTypeGroupBox.setCheckable(False)
        self.CreateAccountChooseAccountTypeGroupBox.setObjectName("CreateAccountChooseAccountTypeGroupBox")
        self.CreateAccountAdministratorRadioButton = QtWidgets.QRadioButton(self.CreateAccountChooseAccountTypeGroupBox)
        self.CreateAccountAdministratorRadioButton.setGeometry(QtCore.QRect(20, 20, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CreateAccountAdministratorRadioButton.setFont(font)
        self.CreateAccountAdministratorRadioButton.setObjectName("CreateAccountAdministratorRadioButton")
        self.CreateAccountOperatorRadioBUtton = QtWidgets.QRadioButton(self.CreateAccountChooseAccountTypeGroupBox)
        self.CreateAccountOperatorRadioBUtton.setGeometry(QtCore.QRect(170, 20, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CreateAccountOperatorRadioBUtton.setFont(font)
        self.CreateAccountOperatorRadioBUtton.setObjectName("CreateAccountOperatorRadioBUtton")
        self.CreateAccountAlreadyHaveAnAccountLbl = QtWidgets.QLabel(self.centralwidget)
        self.CreateAccountAlreadyHaveAnAccountLbl.setGeometry(QtCore.QRect(200, 910, 151, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.CreateAccountAlreadyHaveAnAccountLbl.setFont(font)
        self.CreateAccountAlreadyHaveAnAccountLbl.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"color: rgb(255, 255, 255);")
        self.CreateAccountAlreadyHaveAnAccountLbl.setObjectName("CreateAccountAlreadyHaveAnAccountLbl")
        self.CreateAccountLogInHerePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.CreateAccountLogInHerePushButton.setGeometry(QtCore.QRect(350, 910, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.CreateAccountLogInHerePushButton.setFont(font)
        self.CreateAccountLogInHerePushButton.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"color: rgb(255, 255, 255);")
        self.CreateAccountLogInHerePushButton.setObjectName("CreateAccountLogInHerePushButton")
        self.CreateAccountMiddleNameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.CreateAccountMiddleNameLineEdit.setGeometry(QtCore.QRect(180, 350, 291, 41))
        self.CreateAccountMiddleNameLineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.CreateAccountMiddleNameLineEdit.setMaxLength(64)
        self.CreateAccountMiddleNameLineEdit.setObjectName("CreateAccountMiddleNameLineEdit")
        self.CreateAccountMiddleNameLbl = QtWidgets.QLabel(self.centralwidget)
        self.CreateAccountMiddleNameLbl.setGeometry(QtCore.QRect(180, 330, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.CreateAccountMiddleNameLbl.setFont(font)
        self.CreateAccountMiddleNameLbl.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"color: rgb(255, 255, 255);")
        self.CreateAccountMiddleNameLbl.setObjectName("CreateAccountMiddleNameLbl")
        self.CreateAccountBGLbl.raise_()
        self.CreateAccountCreateUsernameLbl.raise_()
        self.CreateAccountCreateUsernameLineEdit.raise_()
        self.CreateAccountSignUpPushButton.raise_()
        self.CreateAccountCreatePasswordLineEdit.raise_()
        self.CreateAccountLbl.raise_()
        self.CreateAccountLogoLbl.raise_()
        self.CreateAccountCreatePasswordLbl.raise_()
        self.CreateAccountConfirmPasswordLbl.raise_()
        self.CreateAccountConfirmPasswordLineEdit.raise_()
        self.CreateAccountLastNameLineEdit.raise_()
        self.CreateAccountLastNameLbl.raise_()
        self.CreateAccountFirstNameLineEdit.raise_()
        self.CreateAccountFirstNameLbl.raise_()
        self.CreateAccountChooseAccountTypeGroupBox.raise_()
        self.CreateAccountAlreadyHaveAnAccountLbl.raise_()
        self.CreateAccountLogInHerePushButton.raise_()
        self.CreateAccountMiddleNameLineEdit.raise_()
        self.CreateAccountMiddleNameLbl.raise_()
        CreateAccountWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(CreateAccountWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateAccountWindow)
        CreateAccountWindow.setTabOrder(self.CreateAccountFirstNameLineEdit, self.CreateAccountMiddleNameLineEdit)
        CreateAccountWindow.setTabOrder(self.CreateAccountMiddleNameLineEdit, self.CreateAccountLastNameLineEdit)
        CreateAccountWindow.setTabOrder(self.CreateAccountLastNameLineEdit, self.CreateAccountAdministratorRadioButton)
        CreateAccountWindow.setTabOrder(self.CreateAccountAdministratorRadioButton, self.CreateAccountOperatorRadioBUtton)
        CreateAccountWindow.setTabOrder(self.CreateAccountOperatorRadioBUtton, self.CreateAccountCreateUsernameLineEdit)
        CreateAccountWindow.setTabOrder(self.CreateAccountCreateUsernameLineEdit, self.CreateAccountCreatePasswordLineEdit)
        CreateAccountWindow.setTabOrder(self.CreateAccountCreatePasswordLineEdit, self.CreateAccountConfirmPasswordLineEdit)
        CreateAccountWindow.setTabOrder(self.CreateAccountConfirmPasswordLineEdit, self.CreateAccountSignUpPushButton)
        CreateAccountWindow.setTabOrder(self.CreateAccountSignUpPushButton, self.CreateAccountLogInHerePushButton)

    def retranslateUi(self, CreateAccountWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateAccountWindow.setWindowTitle(_translate("CreateAccountWindow", "MainWindow"))
        self.CreateAccountCreateUsernameLineEdit.setPlaceholderText(_translate("CreateAccountWindow", "  Enter Username"))
        self.CreateAccountSignUpPushButton.setText(_translate("CreateAccountWindow", "Sign Up"))
        self.CreateAccountCreatePasswordLineEdit.setPlaceholderText(_translate("CreateAccountWindow", "  Enter Password"))
        self.CreateAccountLbl.setText(_translate("CreateAccountWindow", "CREATE ACCOUNT"))
        self.CreateAccountCreatePasswordLbl.setText(_translate("CreateAccountWindow", "Create Password"))
        self.CreateAccountCreateUsernameLbl.setText(_translate("CreateAccountWindow", "Create Username"))
        self.CreateAccountConfirmPasswordLbl.setText(_translate("CreateAccountWindow", "Confirm Password"))
        self.CreateAccountConfirmPasswordLineEdit.setPlaceholderText(_translate("CreateAccountWindow", "  Confirm Password"))
        self.CreateAccountLastNameLineEdit.setPlaceholderText(_translate("CreateAccountWindow", "  Enter Last Name"))
        self.CreateAccountLastNameLbl.setText(_translate("CreateAccountWindow", "Last Name"))
        self.CreateAccountFirstNameLineEdit.setPlaceholderText(_translate("CreateAccountWindow", "  Enter First Name"))
        self.CreateAccountFirstNameLbl.setText(_translate("CreateAccountWindow", "First Name"))
        self.CreateAccountChooseAccountTypeGroupBox.setTitle(_translate("CreateAccountWindow", "Choose Account Type"))
        self.CreateAccountAdministratorRadioButton.setText(_translate("CreateAccountWindow", "Administrator"))
        self.CreateAccountOperatorRadioBUtton.setText(_translate("CreateAccountWindow", "Operator"))
        self.CreateAccountAlreadyHaveAnAccountLbl.setText(_translate("CreateAccountWindow", "Already have an acount?"))
        self.CreateAccountLogInHerePushButton.setText(_translate("CreateAccountWindow", "Login here"))
        self.CreateAccountMiddleNameLineEdit.setPlaceholderText(_translate("CreateAccountWindow", "  Enter Middle Initial"))
        self.CreateAccountMiddleNameLbl.setText(_translate("CreateAccountWindow", "Middle Initial"))
import Icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateAccountWindow = QtWidgets.QMainWindow()
    ui = Ui_CreateAccountWindow()
    ui.setupUi(CreateAccountWindow)
    CreateAccountWindow.show()
    sys.exit(app.exec_())
